{ pkgs, config, user, ... }:

let
  keyFiles = [
    (pkgs.fetchurl {
      # replace <github_user> with your own ssh key!
      # command to generate the hash:
      # nix-prefetch-url --type sha256 'https://github.com/<github_user>.gpg' | xargs nix hash to-sri --type sha256
      url = "https://github.com/<github_user>.keys";
      hash = "sha256-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx";
    })
  ];
in
{
  # Users
  users = {
    defaultUserShell = pkgs.bash;
    users = {
      ${user} = {
        isNormalUser = true;
        extraGroups = [ "wheel" ];
        home = "/home/${user}";
        shell = pkgs.bash;
        # generated by `mkpasswd -m scrypt`
        initialHashedPassword = "$7$CU..../....qDkQV/MO7behVrojFN4ML/$dz4kD8CE8PV7koHidmGnIboE3NwZrl/4eUYUvXZ5HH9"; # value: passwd
        # /etc/ssh/authorized_keys.d/${user}
        openssh.authorizedKeys.keyFiles = keyFiles;
      };
      root = {
        inherit (config.users.users."${user}") initialHashedPassword;
        openssh.authorizedKeys.keyFiles = keyFiles;
      };
    };
  };
}
