{ pkgs, config, user, ... }:

let
  keyFiles = [
    (pkgs.fetchurl {
      # replace with your own ssh key!
      url = "https://github.com/yqlbu.keys";
      hash = "sha256-msQCFEqniCZtu+m1MMmqFuEJBdKJ3y828+w7ORf/uP4=";
    })
  ];
in
{
  # Users
  users = {
    defaultUserShell = pkgs.bash;
    users = {
      ${user} = {
        isNormalUser = true;
        extraGroups = [ "wheel" ];
        home = "/home/${user}";
        shell = pkgs.bash;
        # generated by `mkpasswd -m scrypt`
        initialHashedPassword = "$7$CU..../....qDkQV/MO7behVrojFN4ML/$dz4kD8CE8PV7koHidmGnIboE3NwZrl/4eUYUvXZ5HH9"; # value: passwd
        # /etc/ssh/authorized_keys.d/${user}
        openssh.authorizedKeys.keyFiles = keyFiles;
      };
      root = {
        inherit (config.users.users."${user}") initialHashedPassword;
        openssh.authorizedKeys.keyFiles = keyFiles;
      };
    };
  };
}
