---
name: (Cron) Synchronize upstream flake inputs
on:
  workflow_dispatch:
  schedule:
    # Run this Action every month at 0:00pm UTC
    - cron: "0 0 1 * *"

env:
  MAINTAINERS: piyoki
  TARGETS: |
    auto-cpufreq
  PR_LABELS: |
    nixpkgs
    pre-commit-hooks
  GIT_COMMIT_MESSAGE: "chore(flake) update flake.lock for the selected upstream inputs"

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub auth token
        # https://github.com/tibdex/github-app-token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - uses: actions/checkout@main
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - name: Update flake.lock
        id: update-flake-lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: ${{ env.GIT_COMMIT_MESSAGE }}
          pr-labels: ${{ env.PR_LABELS }}
          inputs: ${{ env.TARGETS }}
          token: ${{ steps.generate_token.outputs.token }}
          pr-assignees: ${{ env.MAINTAINERS }}

      - name: Print PR number
        run: |
          echo Pull request number is ${{ steps.update.outputs.pull-request-number }}.
